[package]
name = "raphook"
version = "0.1.16"
edition = "2021"
description = "A simple tool to hook git hooks"


[dependencies]
clap = { version = "4.5.27", features = ["derive"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_yaml = "=0.8.26"
log = "0.4"
env_logger = "0.10"