name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux builds
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: raphook-linux-x64
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            artifact_name: raphook-linux-arm64

          # macOS builds
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: raphook-darwin-x64
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: raphook-darwin-arm64

          # Windows builds
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: raphook-windows-x64
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            artifact_name: raphook-windows-arm64

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install cross-compilation tools
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Build binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}

      - name: Prepare package
        shell: bash
        run: |
          mkdir -p dist/${{ matrix.artifact_name }}/bin
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            cp target/${{ matrix.target }}/release/raphook.exe dist/${{ matrix.artifact_name }}/bin/
          else
            cp target/${{ matrix.target }}/release/raphook dist/${{ matrix.artifact_name }}/bin/
          fi
          cp packages/npm/${{ matrix.artifact_name }}/package.json dist/${{ matrix.artifact_name }}/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: dist/${{ matrix.artifact_name }}
