name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  check:
    name: Check version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Get version
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

  build:
    needs: check
    name: Build (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux builds
          # - os: ubuntu-latest
          #   target: x86_64-unknown-linux-gnu
          #   artifact_name: raphook-linux-x64
          # - os: ubuntu-latest
          #   target: aarch64-unknown-linux-gnu
          #   artifact_name: raphook-linux-arm64
          #   use_cross: true

          # macOS builds
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: raphook-darwin-x64
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: raphook-darwin-arm64

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install cross
        if: matrix.use_cross
        run: cargo install cross

      - name: Build binary
        shell: bash
        run: |
          if [ "${{ matrix.use_cross }}" = "true" ]; then
            cross build --release --target ${{ matrix.target }}
          else
            cargo build --release --target ${{ matrix.target }}
          fi

      - name: Prepare package
        shell: bash
        run: |
          mkdir -p dist/${{ matrix.artifact_name }}/bin
          cp target/${{ matrix.target }}/release/raphook ./dist/${{ matrix.artifact_name }}/bin/
          cp packages/npm/${{ matrix.artifact_name }}/package.json ./dist/${{ matrix.artifact_name }}/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ./dist/${{ matrix.artifact_name }}/*
          if-no-files-found: error

  publish:
    needs: [check, build]
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: raphook-*
          path: dist
          merge-multiple: true

      - name: Display current directory
        run: pwd
      - name: Display structure of downloaded files
        run: ls -R

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      # TODO: Create GitHub Release
      # - name: Create GitHub Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     tag_name: ${{ github.ref_name }}
      #     name: Release ${{ github.ref_name }}
      #     draft: false
      #     files: dist/raphook-*
      #     fail_on_unmatched_files: true
      #     generate_release_notes: true
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate npm packages
        run: node packages/npm/raphook/scripts/generate-packages.mjs

      - name: Publish main package
        run: |
          cp ./README.md packages/npm/raphook/README.md
          cd packages/npm/raphook
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
